# Dataset Understanding

This notebook focuses on understanding the basic structure and components of a dataset before performing data analysis or building a machine learning model.

In this notebook, I will cover:

- Dataset
- Features
- Target variable
- Independent and dependent variables
- Numerical and categorical features
- Discrete and continuous features
- Identifier columns
- Metadata
- Dataset dimensions

For each concept, I will first explain it, demonstrate it using examples, and then implement it using Python.

## Selected Dataset: Titanic Dataset

### Dataset Name
Titanic Passenger Dataset

### Business / Domain
Transportation and passenger survival analysis.

### Dataset Description
The dataset contains information about passengers who travelled on the Titanic. It includes details such as passenger class, age, gender, fare, family information, and survival status.

### Number of Records
891 rows

### Number of Columns
15 columns in the commonly used dataset version.

### Important Columns

- `survived` – Indicates whether the passenger survived.
- `pclass` – Passenger class.
- `sex` – Gender of the passenger.
- `age` – Age of the passenger.
- `sibsp` – Number of siblings or spouses aboard.
- `parch` – Number of parents or children aboard.
- `fare` – Ticket fare.
- `embarked` – Port where the passenger boarded.

### Target Variable
The `survived` column is used as the target variable. It represents whether a passenger survived or not.

### Why I Selected This Dataset

I selected the Titanic dataset because it contains both numerical and categorical features. It also contains missing values and different types of variables, making it suitable for practicing dataset understanding, inspection, preprocessing, and machine learning concepts.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset("titanic")

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 1. What is a Dataset?

A dataset is a collection of related information organized in a structured format. In data analysis, a dataset usually contains rows and columns.

- Each row represents one observation or record.
- Each column represents one characteristic or variable.

For example, in the Titanic dataset, each row represents a passenger, while columns such as age, sex, fare, and survived describe that passenger.

### Real-world Example
A company may maintain a dataset containing information about its customers.

### Business Example
An e-commerce company can store customer ID, product purchased, quantity, price, and payment method in a dataset.

### AI/ML Use Case
Datasets are used to train, validate, and test machine learning models.

### Importance
Understanding the dataset is the first step before cleaning data, performing analysis, or building an ML model.

In [2]:
# Display the first five records
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

The `head()` method displays the first five rows of the dataset.

This helps us understand:

- What information is available
- How the columns are organized
- The type of values present in the dataset

The initial inspection gives a basic understanding of the data before further analysis.

## 2. What is a Feature?

A feature is a column or variable that provides information about an observation.

In machine learning, features are generally used as input variables to help a model make predictions.

For example, in the Titanic dataset:

- Age
- Sex
- Passenger class
- Fare

can be used as features to predict passenger survival.

### Simple Example
If we want to predict house prices, the size of the house and number of bedrooms can be features.

### Business Example
In customer churn prediction, customer age, subscription type, monthly charges, and usage can be features.

### AI/ML Use Case
Features are the inputs given to a machine learning model.

### Importance
The quality and relevance of features can directly affect model performance.

In [3]:
# Display selected features
features = df[["pclass", "sex", "age", "fare"]]

features.head()

   pclass     sex   age     fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

Here, `pclass`, `sex`, `age`, and `fare` are selected as example features.

These columns contain information that may help a machine learning model predict passenger survival.

## 3. What is a Target Variable?

A target variable is the output that we want to predict in a machine learning problem.

In the Titanic dataset, the target variable is `survived`.

- `0` represents a passenger who did not survive.
- `1` represents a passenger who survived.

### Simple Example
For house price prediction, the house price is the target variable.

### Business Example
In customer churn analysis, the churn status is the target variable.

### AI/ML Use Case
A supervised machine learning model learns the relationship between features and the target variable.

### Importance
The target variable defines the main prediction problem that the machine learning model needs to solve.

In [4]:
# Display the target variable
df["survived"].head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: survived, dtype: int64

The `survived` column is the target variable in this dataset.

A machine learning model can use passenger-related features to predict the values in this column.

## 4. Independent Variables

Independent variables are the input variables used to explain or predict another variable.

In a machine learning model, independent variables are usually called features.

For the Titanic dataset, examples include:

- Age
- Sex
- Passenger class
- Fare

These variables can be used to predict whether a passenger survived.

### Business Example
In a loan approval system, income, credit score, and employment status can be independent variables.

### AI/ML Use Case
Independent variables are provided as input to the machine learning algorithm.

### Importance
Selecting useful independent variables can improve the accuracy and reliability of a model.

In [5]:
# Example independent variables
X = df[["pclass", "sex", "age", "fare"]]

X.head()

   pclass     sex   age     fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

The variable `X` contains the independent variables.

These columns can later be used as input features for a machine learning model.

## 5. Dependent Variables

A dependent variable is the variable whose value depends on other variables.

In machine learning, the dependent variable is generally the target variable.

In the Titanic dataset, `survived` is the dependent variable because we are interested in predicting survival based on passenger information.

### Business Example
In sales prediction, sales amount can be the dependent variable.

### AI/ML Use Case
The machine learning model attempts to predict the dependent variable using independent variables.

### Importance
The dependent variable represents the final outcome of the prediction problem.

In [6]:
# Dependent variable
y = df["survived"]

y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

The variable `y` contains the dependent or target variable.

The machine learning model will attempt to predict these values using the features stored in `X`.

## 6. Numerical Features

Numerical features contain values represented by numbers.

These features can be used for mathematical and statistical calculations.

Examples from the Titanic dataset include:

- Age
- Fare
- Passenger class
- Number of siblings or spouses

### Business Example
In an e-commerce dataset, product price, quantity, and discount percentage are numerical features.

### AI/ML Use Case
Numerical features can be directly used by many machine learning algorithms after appropriate preprocessing.

### Importance
Numerical features help us calculate statistics such as mean, median, minimum, maximum, and standard deviation.

In [1]:
import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Loading the Dataset

The Titanic dataset is loaded into the notebook using the Pandas library.  
The `read_csv()` function reads the `Titanic-Dataset.csv` file and stores it in a DataFrame named `df`.

The `df.head()` function displays the first five rows of the dataset. This helps us verify that the dataset has been loaded successfully and understand its initial structure.

## 7. Categorical Features

Categorical features contain values that represent categories or groups.

Examples from the Titanic dataset include:

- Sex
- Embarked
- Class
- Deck

### Simple Example
Gender can contain categories such as male and female.

### Business Example
Payment methods such as credit card, cash, and UPI are categorical features.

### AI/ML Use Case
Machine learning models generally require categorical values to be converted into a numerical representation before training.

### Importance
Categorical features can provide important information about groups and patterns within the data.

### Categorical Features

Categorical features contain text or label-based values rather than numerical values. In the Titanic dataset, columns such as `Name`, `Sex`, `Ticket`, `Cabin`, and `Embarked` are categorical features.

The `select_dtypes()` function is used to identify and display these categorical columns. This helps us understand the non-numerical information available in the dataset.

In [5]:
# Display categorical columns
categorical_features = df.select_dtypes(include=["str", "object", "category"])

categorical_features.head()

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S

This code identifies columns containing categorical information.

For machine learning, these values may later require encoding into numerical form. For example, categories can be converted using techniques such as label encoding or one-hot encoding.

## 8. Discrete Features

Discrete features contain countable values and usually take specific separate values.

They generally represent counts.

Examples from the Titanic dataset include:

- `sibsp` – Number of siblings or spouses
- `parch` – Number of parents or children

A person cannot have 2.5 siblings, so these values are discrete.

### Business Example
Number of products purchased by a customer is a discrete feature.

### AI/ML Use Case
Discrete features can provide useful information about counts and frequency patterns.

### Importance
Understanding whether a variable is discrete helps in selecting appropriate analysis and preprocessing techniques.

In [7]:
# Display discrete features
discrete_features = df[["SibSp", "Parch"]]

discrete_features.head(10)

   SibSp  Parch
0      1      0
1      1      0
2      0      0
3      1      0
4      0      0
5      0      0
6      0      0
7      3      1
8      0      2
9      1      0

**Interpretation:**

The output displays the `SibSp` and `Parch` columns for the first 10 passengers. These columns contain countable numerical values and are therefore discrete features.

These features can help analyze family relationships and the size of family groups travelling on the Titanic.

### 9. Continuous Features

Continuous features are numerical features that can take a wide range of values, including decimal values.

**Real-world Example:**

Height and weight are continuous features because they can contain decimal values, such as 172.5 cm or 65.8 kg.

**Business Example:**

In an e-commerce dataset, product price, revenue, and customer spending can be continuous features.

**AI/ML Example:**

Continuous features can be used by machine learning models to identify numerical patterns and make predictions. For example, passenger age and ticket fare may influence the probability of survival.

**Importance:**

Continuous features are important for statistical analysis because we can calculate measures such as mean, median, standard deviation, minimum, and maximum.

In the Titanic dataset, `Age` and `Fare` are examples of continuous numerical features.

In [8]:
# Display continuous features
continuous_features = df[["Age", "Fare"]]

continuous_features.head(10)

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

**Interpretation:**

The output displays the `Age` and `Fare` values for the first 10 passengers.

These columns contain numerical values that can include decimals, making them continuous features. They can be analyzed to understand the age distribution of passengers and the variation in ticket prices.

### 10. Identifier Columns

An identifier column is used to uniquely identify each record in a dataset.

**Real-world Example:**

A student ID uniquely identifies each student in a college database.

**Business Example:**

A company may use a customer ID to uniquely identify each customer and track their transactions.

**AI/ML Example:**

Identifier columns are generally not used directly as predictive features because the identification number itself usually does not contain meaningful information about the target variable.

**Importance:**

Identifier columns help distinguish individual records and maintain data integrity.

In the Titanic dataset, `PassengerId` is an identifier column because each passenger has a unique identification number.

In [9]:
# Display identifier column
df["PassengerId"].head(10)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: PassengerId, dtype: int64

**Interpretation:**

The output displays the first 10 passenger identification numbers.

Each `PassengerId` value is used to identify a specific passenger. This column is useful for identifying records, but it generally should not be used directly as a predictive feature in a machine learning model.

### 11. Target Variable

The target variable is the output variable that a machine learning model attempts to predict.

**Real-world Example:**

A bank may use customer information to predict whether a customer will default on a loan.

**Business Example:**

A company may use customer information to predict whether a customer will purchase a product or leave the company.

**AI/ML Example:**

In a classification problem, the target variable contains categories or classes that the machine learning model predicts.

**Importance:**

Understanding the target variable is important because it determines the type of machine learning problem and the objective of the model.

In the Titanic dataset, `Survived` is the target variable.

- `0` represents a passenger who did not survive.
- `1` represents a passenger who survived.

This is a binary classification problem.

In [10]:
# Display target variable distribution
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

**Interpretation:**

The output shows the number of passengers who survived and the number of passengers who did not survive.

The `Survived` column is the target variable because a machine learning model can use passenger features such as age, sex, passenger class, fare, and family information to predict whether a passenger survived.

### 12. Metadata

Metadata means information that describes a dataset and provides details about its structure.

**Examples of Metadata:**

- Dataset name
- Number of rows
- Number of columns
- Column names
- Data types
- Missing values
- Description of important columns
- Target variable

**Real-world Example:**

A company database may contain metadata describing the names of columns, data types, number of records, and the meaning of each field.

**Business Example:**

Metadata helps analysts and business teams understand what information is available before making decisions based on the data.

**AI/ML Example:**

Before building a machine learning model, metadata helps identify numerical features, categorical features, missing values, identifier columns, and the target variable.

**Importance:**

Metadata helps us understand the structure and quality of a dataset before performing analysis, preprocessing, or machine learning.

For the Titanic dataset, metadata can include column names, data types, non-null values, and memory usage.

In [11]:
# Display dataset metadata
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

**Interpretation:**

The output provides information about the Titanic dataset, including the number of entries, column names, non-null values, and data types.

This information helps identify numerical and categorical columns and also helps detect columns containing missing values.

### 13. Dataset Dimensions

Dataset dimensions describe the size of a dataset in terms of the number of rows and columns.

**Real-world Example:**

A dataset with 1,000 customers and 15 recorded characteristics has 1,000 rows and 15 columns.

**Business Example:**

The number of rows can represent the number of customers, transactions, employees, or products, while the number of columns represents the information collected about each record.

**AI/ML Example:**

Dataset dimensions help us understand the amount of training data and the number of available features before building a machine learning model.

**Importance:**

Understanding dataset dimensions helps us determine the size and structure of the data before performing analysis and machine learning.

In the Titanic dataset, each row represents a passenger, while each column represents information about that passenger.

In [12]:
# Display dataset dimensions
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Dataset Shape:", df.shape)

Number of Rows: 891
Number of Columns: 12
Dataset Shape: (891, 12)

**Interpretation:**

The output displays the number of rows and columns in the Titanic dataset.

The number of rows represents the total number of passenger records, while the number of columns represents the number of variables or characteristics available for each passenger.

## Conclusion

The Titanic dataset was successfully loaded and inspected. The dataset contains different types of features, including numerical, categorical, discrete, continuous, and identifier-related columns. Exploratory analysis helps us understand the structure, characteristics, and relationships within the dataset before performing further analysis or machine learning.